[package]
name = "x25519-dalek"
version = "0.3.0"
authors = ["Isis Lovecruft <isis@patternsinthevoid.net>"]
readme = "README.md"
license = "BSD-3-Clause"
repository = "https://github.com/dalek-cryptography/x25519-dalek"
homepage = "https://dalek.rs/"
documentation = "https://docs.rs/x25519-dalek"
categories = ["cryptography", "no-std"]
keywords = ["cryptography", "curve25519", "key-exchange", "x25519", "diffie-hellman"]
description = "X25519 elliptic curve Diffie-Hellman key exchange in pure-Rust, using curve25519-dalek."
exclude = [
    ".gitignore",
    ".travis.yml",
    "CONTRIBUTING.md",
]

[badges]
travis-ci = { repository = "dalek-cryptography/x25519-dalek", branch = "master"}

[dependencies.curve25519-dalek]
version = "^0.19"
default-features = false

[dependencies.rand_core]
default-features = false
version = "0.2"

[dev-dependencies]
criterion = "0.2"
rand = "0.5"

[dependencies.clear_on_drop]
version = "0.2"

[[bench]]
name = "x25519"
harness = false

[features]
default = ["std", "nightly", "u64_backend"]
std = ["curve25519-dalek/std"]
nightly = ["curve25519-dalek/nightly", "clear_on_drop/nightly"]
u64_backend = ["curve25519-dalek/u64_backend"]
u32_backend = ["curve25519-dalek/u32_backend"]
